---
title: "Data605 - Assignment12"
author: "Kishore Prasad"
date: "Nov 10, 2016"
output: html_document
---

##Problem set 1

Using the stats and boot libraries in R perform a cross-validation experiment to observe the bias variance tradeoff. You'll use the auto data set from previous assignments. This dataset has 392 observations across 5 variables. We want to fit a polynomial model of various degrees using the glm function in R and then measure the cross validation error
using cv.glm function.

Fit various polynomial models to compute mpg as a function of the other four variables acceleration, weight, horsepower, and displacement using glm function. For example:

glm.fit=glm(mpg~poly(disp+hp+wt+acc,2), data=auto)
cv.err5[2]=cv.glm(auto,glm.fit,K=5)$delta[1]

will fit a 2nd degree polynomial function between mpg and the remaining 4 variables and perform 5 iterations of cross-validations. This result will be stored in a cv.err5 array. cv.glm returns the estimated cross validation error and its adjusted value in a variable called delta. Please see the help on cv.glm to see more information. 


**Answer:**

We will conduct the experiment for degrees from 1 to 8. In each case, we will generate the cross validation error array for 5 iterations.

```{r, warning=FALSE, message=FALSE}
library(stats)
library(boot)
library(dplyr)
library(ggplot2)

# Assuming that the data file is located in the working directory.


autodata <- read.table('auto-mpg.data', col.names=c('displacement', 'horsepower', 'weight', 'acceleration', 'mpg'))

Num_Degrees <- 8
Num_Iterations <- 5
cv.errors <- c()

for(i in 1:Num_Degrees) {

    # N degree polynomial function between mpg and the remaining 4 variables
    glm.fit <- glm(mpg~poly(displacement+horsepower+weight+acceleration,i), data=autodata)
    
    
    # Perform 10 iterations of cross-validations and add to existing array of errors. 
    cv.errors = c(cv.errors, cv.glm(autodata,glm.fit,K=Num_Iterations)$delta[1] ) 

}

# Plot the cross validation error function 

degree=1:8

plot(degree,cv.errors,type='b')

```
