---
title: "Data605 - Assignment3"
author: "Kishore Prasad"
date: "September 11, 2016"
output: html_document
---


##Problem set 1


#####(1) What is the rank of the matrix A?

$A = \begin{bmatrix} 1 & 2 & 3 & 4 \\ -1 & 0 & 1 & 3 \\ 0 & 1 & -2 & 1 \\ 5 & 4 & -2 & -3 \end{bmatrix}$

**Answer:**

To solve this, lets reduce the matrix by elimination:

$r2\rightarrow r2-(-1)r1$ gives $A = \begin{bmatrix} 1 & 2 & 3 & 4 \\ 0 & 2 & 4 & 7 \\ 0 & 1 & -2 & 1 \\ 5 & 4 & -2 & -3 \end{bmatrix}$

$r4\rightarrow r4-(5)r1$ gives $A = \begin{bmatrix} 1 & 2 & 3 & 4 \\ 0 & 2 & 4 & 7 \\ 0 & 1 & -2 & 1 \\ 0 & -6 & -17 & -23 \end{bmatrix}$

$r3\rightarrow r3-(\frac { 1 }{ 2 } )r2$ gives $A = \begin{bmatrix} 1 & 2 & 3 & 4 \\ 0 & 2 & 4 & 7 \\ 0 & 0 & -4 & \frac { -5 }{ 2 } \\ 0 & -6 & -17 & -23 \end{bmatrix}$

$r4\rightarrow r4+(3)r2$ gives $A = \begin{bmatrix} 1 & 2 & 3 & 4 \\ 0 & 2 & 4 & 7 \\ 0 & 0 & -4 & \frac { -5 }{ 2 } \\ 0 & 0 & -5 & -2 \end{bmatrix}$

$r4\rightarrow r4-(\frac { 5 }{ 4 } )r3$ gives $A = \begin{bmatrix} 1 & 2 & 3 & 4 \\ 0 & 2 & 4 & 7 \\ 0 & 0 & -4 & \frac { -5 }{ 2 } \\ 0 & 0 & 0 & \frac { 9 }{ 8 } \end{bmatrix}$


Given that we are able to reduce the matrix to its row elcheon form and retaining all the pivots, we can conclude that the matrix has the same rank as its dimensions.

i.e it has a rank of 4. 



\
\




#####(2) Given an mxn matrix where m > n, what can be the maximum rank? The minimum rank, assuming that the matrix is non-zero?

**Answer:**

The maximum rank could be min(m, n) i.e **n** (given m > n). 

Given that the matrix is non-zero the minimum rank would be **1**.




\
\



#####(3) What is the rank of matrix B?

$B = \begin{bmatrix} 1 & 2 & 1 \\ 3 & 6 & 3 \\ 2 & 4 & 2 \end{bmatrix}$

**Answer:**

To solve this, lets reduce the matrix by elimination:

$r2\rightarrow r2-(3)r1$ gives $B = \begin{bmatrix} 1 & 2 & 1 \\ 0 & 0 & 0 \\ 2 & 4 & 2 \end{bmatrix}$

$r3\rightarrow r3-(2)r1$ gives $B = \begin{bmatrix} 1 & 2 & 1 \\ 0 & 0 & 0 \\ 0 & 0 & 0 \end{bmatrix}$


Since we have only 1 linearly independent row now, the rank of this matrix is 1.


\
\



##Problem set 2

Compute the eigenvalues and eigenvectors of the matrix A. You'll need to show your work. You'll need to write out the characteristic polynomial and show your solution.

$A = \begin{bmatrix} 1 & 2 & 3 \\ 0 & 4 & 5 \\ 0 & 0 & 6 \end{bmatrix}$

**Answer:**

$\lambda$ is an Eigen value of A if and only if $det(\lambda \times I - A)=0$

solving for the above, we get:

det($\begin{bmatrix} \lambda & 0 & 0 \\ 0 & \lambda & 0 \\ 0 & 0 & \lambda \end{bmatrix} - \begin{bmatrix} 1 & 2 & 3 \\ 0 & 4 & 5 \\ 0 & 0 & 6 \end{bmatrix}$) = 0



det($\begin{bmatrix} (\lambda-1 & -2 & -3 \\ 0 & (\lambda-4) & -5 \\ 0 & 0 & (\lambda-6) \end{bmatrix}$) = 0



Simplifying the above by applying the steps for determinants, we get 

$(\lambda-1) \times (\lambda-4) \times (\lambda-6) = 0$


$(\lambda-1) \times ({ \lambda  }^{ 2 }-10\lambda +24) = 0$


Multiplying the terms, we get the characteristic polynomial as:

**${\lambda}^{3} - 11{\lambda}^{2} + 34\lambda - 24) = 0$**


Also, given that $(\lambda-1) \times (\lambda-4) \times (\lambda-6) = 0$, we can conclude that the following values of $\lambda$ solve the above characteristic polynomial : 1, 4, 6.

**So the Eigen values are  ${\lambda}_{1} =  1$ and ${\lambda}_{2} =  4$ and ${\lambda}_{3} = 6$.**

Lets now find the Eigen vectors.


When we use ${\lambda}_{1} = 1$ in the definition of Eigen value:

$A\upsilon - \lambda \upsilon  =  (A - \lambda I)\upsilon =0$

$(\begin{bmatrix} 1 & 2 & 3 \\ 0 & 4 & 5 \\ 0 & 0 & 6 \end{bmatrix} - \begin{bmatrix} 1 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 1 \end{bmatrix}) \begin{bmatrix} { \upsilon  }_{ 1 } \\ { \upsilon  }_{ 2 } \\ { \upsilon  }_{ 3 } \end{bmatrix} = 0$


$(\begin{bmatrix} 0 & 2 & 3 \\ 0 & 3 & 5 \\ 0 & 0 & 5 \end{bmatrix}) \begin{bmatrix} { \upsilon  }_{ 1 } \\ { \upsilon  }_{ 2 } \\ { \upsilon  }_{ 3 } \end{bmatrix} = 0$

Using Gaussian elimination on the above:


$r2\rightarrow r2-(\frac { 3 }{ 2 })r1$ gives $\begin{bmatrix} 0 & 2 & 3 \\ 0 & 0 & (\frac { 1 }{ 2 }) \\ 0 & 0 & 5 \end{bmatrix}$

$r2\rightarrow r2 \times 2$ gives $\begin{bmatrix} 0 & 2 & 3 \\ 0 & 0 & 1 \\ 0 & 0 & 5 \end{bmatrix}$


$r3\rightarrow r3-5r2$ gives $\begin{bmatrix} 0 & 2 & 3 \\ 0 & 0 & 1 \\ 0 & 0 & 0 \end{bmatrix}$


$r1\rightarrow r1-3r2$ gives $\begin{bmatrix} 0 & 2 & 0 \\ 0 & 0 & 1 \\ 0 & 0 & 0 \end{bmatrix}$


Finally, $r1\rightarrow \frac { r1 }{ 2 }$ gives $\begin{bmatrix} 0 & 1 & 0 \\ 0 & 0 & 1 \\ 0 & 0 & 0 \end{bmatrix}$

Solving for this, we get:

${\upsilon}_{2} = 0$
${\upsilon}_{3} = 0$

${\upsilon}_{1}$ did not show up in the set of equations, therefore regardless of its value:


$\begin{bmatrix} 0 & 1 & 0 \\ 0 & 0 & 1 \\ 0 & 0 & 0 \end{bmatrix} \begin{bmatrix} { \upsilon  }_{ 1 } \\ 0 \\ 0 \end{bmatrix} = 0$

Let ${ \upsilon  }_{ 1 } = 1$ 

Then the first Eigen vector is: 

**v = (1, 0, 0)**


Solving similarly for ${\lambda}_{2} = 4$, we get the Eigen Vector as:


$(\begin{bmatrix} 1 & 2 & 3 \\ 0 & 4 & 5 \\ 0 & 0 & 6 \end{bmatrix} - \begin{bmatrix} 4 & 0 & 0 \\ 0 & 4 & 0 \\ 0 & 0 & 4 \end{bmatrix}) \begin{bmatrix} { \upsilon  }_{ 1 } \\ { \upsilon  }_{ 2 } \\ { \upsilon  }_{ 3 } \end{bmatrix} = 0$


$(\begin{bmatrix} -3 & 2 & 3 \\ 0 & 0 & 5 \\ 0 & 0 & 2 \end{bmatrix}) \begin{bmatrix} { \upsilon  }_{ 1 } \\ { \upsilon  }_{ 2 } \\ { \upsilon  }_{ 3 } \end{bmatrix} = 0$

Using Gaussian elimination on the above:


$r1\rightarrow (\frac { -1 }{ 3 })r1$ gives $\begin{bmatrix} 1 & \frac { -2 }{ 3 } & -1 \\ 0 & 0 & 5 \\ 0 & 0 & 2 \end{bmatrix}$


$r2\rightarrow (\frac { 1 }{ 5 })r2$ gives $\begin{bmatrix} 1 & \frac { -2 }{ 3 } & -1 \\ 0 & 0 & 1 \\ 0 & 0 & 2 \end{bmatrix}$

$r3\rightarrow r3 - 2r2$ gives $\begin{bmatrix} 1 & \frac { -2 }{ 3 } & -1 \\ 0 & 0 & 1 \\ 0 & 0 & 0 \end{bmatrix}$

Finally, $r1\rightarrow r1 - (-1)r2$ gives $\begin{bmatrix} 1 & \frac { -2 }{ 3 } & 0 \\ 0 & 0 & 1 \\ 0 & 0 & 0 \end{bmatrix}$

Assuming ${\upsilon}_{2}=y$ and Solving for this, we get:

${\upsilon}_{1} = \frac { 2 }{ 3 } y$
${\upsilon}_{2} = y$
${\upsilon}_{3} = 0$


$\begin{bmatrix} 0 & 1 & 0 \\ 0 & 0 & 1 \\ 0 & 0 & 0 \end{bmatrix} \begin{bmatrix}  \frac { 2 }{ 3 } y \\ y \\ 0 \end{bmatrix} = 0$

Let y=1, then the second Eigen vector is: 

**v = ($\frac { 2 }{ 3 }$, 1, 0)**




Solving similarly for ${\lambda}_{3} = 6$, we get the Eigen Vector as:


$(\begin{bmatrix} 1 & 2 & 3 \\ 0 & 4 & 5 \\ 0 & 0 & 6 \end{bmatrix} - \begin{bmatrix} 6 & 0 & 0 \\ 0 & 6 & 0 \\ 0 & 0 & 6 \end{bmatrix}) \begin{bmatrix} { \upsilon  }_{ 1 } \\ { \upsilon  }_{ 2 } \\ { \upsilon  }_{ 3 } \end{bmatrix} = 0$


$(\begin{bmatrix} -5 & 2 & 3 \\ 0 & -2 & 5 \\ 0 & 0 & 0 \end{bmatrix}) \begin{bmatrix} { \upsilon  }_{ 1 } \\ { \upsilon  }_{ 2 } \\ { \upsilon  }_{ 3 } \end{bmatrix} = 0$

Using Gaussian elimination on the above:


$r1\rightarrow (\frac { -1 }{ 5 })r1$ gives $\begin{bmatrix} 1 & \frac { -2 }{ 5 } & \frac { -3 }{ 5 } \\ 0 & -2 & 5 \\ 0 & 0 & 0 \end{bmatrix}$


$r2\rightarrow (\frac { -1 }{ 2 })r2$ gives $\begin{bmatrix} 1 & \frac { -2 }{ 5 } & \frac { -3 }{ 5 } \\ 0 & 1 & \frac { -5 }{ 2 } \\ 0 & 0 & 0 \end{bmatrix}$

Finally, $r1\rightarrow r1 - (\frac { -2 }{ 5 })r2$ gives $\begin{bmatrix} 1 & 0 & \frac { -8 }{ 5 } \\ 0 & 1 & \frac { -5 }{ 2 } \\ 0 & 0 & 0 \end{bmatrix}$



Assuming ${\upsilon}_{3}=z$ and Solving for this, we get:

${\upsilon}_{1} = \frac { 8 }{ 5 } z$
${\upsilon}_{2} = \frac { 5 }{ 2 } z$
${\upsilon}_{3} = z$


$\begin{bmatrix} 0 & 1 & 0 \\ 0 & 0 & 1 \\ 0 & 0 & 0 \end{bmatrix} \begin{bmatrix}  \frac { 8 }{ 5 } z \\ \frac { 5 }{ 2 } z \\ z \end{bmatrix} = 0$

Let z=1, then the third  Eigen vector is: 

**v = ($\frac { 8 }{ 5 }$, $\frac { 5 }{ 2 }$, 1)**



